import Dexie, { type Table } from 'dexie';
export type StoredSnapshot = {
  id:string;
  parentId?:string;
  createdAt:number;
  generatedImage:string;
  generatedImageDataUrl?:string;
  prompt:string;
  note:string;
  selectedBackend?:string;
  selectedModel?:string;
  importedImage?:string;
  importedImageDataUrl?:string;
  humanDrawLayer?:[number,number][];
  humanDrawLayerDataUrl?:string;
  guideEraseMask?:string;
  guideEraseMaskDataUrl?:string;
  guideComposite?:string;
  guideCompositeDataUrl?:string;
  lastNoiseMask?:[number,number][];
  diffusionStepCount?:number;
  seed?:number;
  cfg?:number;
  globalExplorationNoiseStrength?:number;
  explorationRewindFrames?:number;
  explorationNoiseSteps?:number;
  localRejectionStrength?:number;
  guideInfluence?:number;
  temperature?:number;
  runtimeSnapshotId?:string;
  runtimeSessionId?:string;
};
class SnapshotDatabase extends Dexie { snapshots!: Table<StoredSnapshot,string>; constructor(){super('live-diffusion-canvas');this.version(1).stores({snapshots:'id,createdAt'});} }
export const snapshotDb = new SnapshotDatabase();
export const loadSnapshots = () => snapshotDb.snapshots.orderBy('createdAt').toArray();
export const persistSnapshot = (snapshot:StoredSnapshot) => snapshotDb.snapshots.put(snapshot);
export const clearSnapshots = () => snapshotDb.snapshots.clear();
